
vscode:
  extensions:
    - formulahendry.auto-close-tag
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-toolsai.vscode-jupyter-cell-tags
  - ms-toolsai.vscode-jupyter-cell-tags
oolsai.vscode-jupyter-cell-tags
